### ISSUE TITLE
To-Do Before Release:

### ISSUE THREAD

**Issue by Chuckleberry-Finn** [Chuckleberry-Finn/game-night#4]
- [x] Search Function UI
- [x] Support for additional context actions (API)
- [x] Models
- [x] Drag drop from inventory to window
- [x] Add copyright for Uno/Catan to steam
- [x] Add readme to github
